// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCneGvLNW-kvkt04KCfie5URpeFMK-URME',
    appId: '1:270189702621:web:8b818aaca81faae121da34',
    messagingSenderId: '270189702621',
    projectId: 'billings-app-77b3e',
    authDomain: 'billings-app-77b3e.firebaseapp.com',
    storageBucket: 'billings-app-77b3e.firebasestorage.app',
    measurementId: 'G-XW32ERSDM5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn9h6RBvUAbsPPHKDNQcRaRhw9p9WL6zU',
    appId: '1:270189702621:ios:7319177c89e75da821da34',
    messagingSenderId: '270189702621',
    projectId: 'billings-app-77b3e',
    storageBucket: 'billings-app-77b3e.firebasestorage.app',
    iosBundleId: 'com.tushal.billings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCneGvLNW-kvkt04KCfie5URpeFMK-URME',
    appId: '1:270189702621:web:ff95e167d7a8ee0621da34',
    messagingSenderId: '270189702621',
    projectId: 'billings-app-77b3e',
    authDomain: 'billings-app-77b3e.firebaseapp.com',
    storageBucket: 'billings-app-77b3e.firebasestorage.app',
    measurementId: 'G-2F5JXZNG11',
  );
}
